### ISSUE TITLE
watch-deps doesn't react to changes

### ISSUE THREAD

**Issue by maxthoursie** [lambdaisland/classpath#3]
After running `(watch-deps/start! {})` and then changing `deps.edn`, I don't see the printed message and the classpath-chain haven't changed. Some experimentation seems to indicate that beholder doesn't get any event.

This is on a Mac using Calva.

Manually running the code inside the on-event handler in watch-deps works as intended. It correctly loads the newly added lib in deps to the classspath.

As a side note, it would be great if the body of watch-deps was a separate public fn, so I easily can reload the deps.edn file on demand without running the watcher.

Thank you for tackling a problem that needs a solution!

**Comment by plexus** [comment]
Maybe file an issue on Beholder?

> As a side note, it would be great if the body of watch-deps was a separate public fn, so I easily can reload the deps.edn file on demand without running the watcher.

You're looking for `lambdaisland.classpath/update-classpath!`

**Comment by maxthoursie** [comment]
`lambdaisland.classpath/update-classpath!` is indeed the one, thank you. I was surprised that watch-deps didn't use it internally but I see now that it does some additional logging.

Will look into filing an issue to beholder.

**Comment by maxthoursie** [comment]
It turns out that Beholder did what it should, but I didn't see the messages in the Calva repl. I used tap> to debug instead to get around that. 

My system reports the path as an absolut path, so the `= "./deps.edn"` test fails and the new dependencies are never installed. Using `str/ends-with?` instead solved the issue.

In addition, watching on `"."` triggers an update every second on `./.calva/output-window/output.calva-repl`. Whether that actually matters or not I don't know, but I filtered it out by only looking for changes in the "./deps.edn" file.

I can submit a PR if you'd like.

**Comment by plexus** [comment]
That would be great. My impression was that beholder could only watch
directories, not individual files.

**Comment by maxthoursie** [comment]
Here's the tiny change: #4 

I did not include the watching on deps.edn only, because I couldn't find any documentation on that watching files is supported (like you said) so I am worried it won't work everywhere even though it works for me.

**Comment by alysbrooks** [comment]
Watching single files doesn't work on Windows (and it may only work on macOS), so not trying to watch just a single file was the right decision for #4. There's also some discussion in #7 about how watching works.

As far as I can tell, #4 fixes this and #7 covers the case for just watching a single file. Feel free to re-open if you experience this issue (or open a new issue).
